### ISSUE TITLE
[transmission] Missing Themes

### ISSUE THREAD

**Issue by nicholaswilde** [k8s-at-home/container-images#102]
# Details

**Image name:** Transmission

**What steps did you take and what happened:**

1. Installed transmission via k8s@home helm chart version 4.0.0 that references this new image.
2. Set `env.TRANSMISSION_WEB_HOME` to  `/kettu/` per the variables specified in the original lsio docker image. The Chart does say that environmental variables can be 
3. Went to https://<host>/transmission/web/ and got a `404` error.

**What did you expect to happen:**

Transmission shows up using the `kettu` front end.

**Anything else you would like to add:**

I haven't tested it, but looking at the code, it looks as if the other `env.TRANSMISSION_WEB_HOME` values won't work either. We can either add the front ends to the image or state that  `env.TRANSMISSION_WEB_HOME` variable should not be used in the chart.

**Additional Information:**

- [LSIO Docker file](https://github.com/linuxserver/docker-transmission/blob/8d6171de6dbc70046f524f20589af346a9e97692/Dockerfile#L33-L62)
- [k8s@home helm chart comment](https://github.com/k8s-at-home/charts/blob/85dd0703b9114b61e10f98711461ce15c9c68973/charts/stable/transmission/values.yaml#L17).

**Comment by onedr0p** [comment]
Opps forgot to clean up the LSIO nonsense from that file. As of right now I have not tested adding in a theme for transmission

**Comment by onedr0p** [comment]
Theroically one could `curl` it to `/config/kettu` nad update the Envar to point to that directory

**Comment by nicholaswilde** [comment]
> I would advise against including these in our images by default (at least for now)

Sounds good to me. I guess we can go ahead and close this issue.

**Comment by onedr0p** [comment]
We can keep it open and maybe document it somwhere.

**Comment by jr0dd** [comment]
for some odd reason the flood ui works still with the env var set in values.yaml. there is nothing in my config directory.
`TRANSMISSION_WEB_HOME: "/flood-for-transmission/"`

```
truenas-scale transmission # ls -laRh /mnt/deadpool/docker/datastore/transmission
/mnt/deadpool/docker/datastore/transmission:
total 77K
drwxr-xr-x  5 1000 1000    9 Apr 19 09:47 .
drwxr-xr-x 16 root root   16 Apr 18 21:17 ..
drwxr-xr-x  2 1000 1000    2 Apr 17 14:04 blocklists
-rw-------  1 1000 1000 1.1K Apr 19 09:47 dht.dat
drwxr-xr-x  2 1000 1000    2 Apr 17 15:55 resume
-rwxr-xr-x  1 1000 1000    0 Apr 17 14:04 settings.json
-rw-------  1 1000 1000  139 Apr 17 15:55 stats.json
drwxr-xr-x  2 1000 1000    2 Apr 17 15:55 torrents
-rwxr-xr-x  1 1000 1000   94 Apr 17 15:38 unrar.sh

/mnt/deadpool/docker/datastore/transmission/blocklists:
total 9.0K
drwxr-xr-x 2 1000 1000 2 Apr 17 14:04 .
drwxr-xr-x 5 1000 1000 9 Apr 19 09:47 ..

/mnt/deadpool/docker/datastore/transmission/resume:
total 33K
drwxr-xr-x 2 1000 1000 2 Apr 17 15:55 .
drwxr-xr-x 5 1000 1000 9 Apr 19 09:47 ..

/mnt/deadpool/docker/datastore/transmission/torrents:
total 33K
drwxr-xr-x 2 1000 1000 2 Apr 17 15:55 .
drwxr-xr-x 5 1000 1000 9 Apr 19 09:47 ..
```
¯\_(ツ)_/¯

**Comment by onedr0p** [comment]
Added https://github.com/k8s-at-home/charts/pull/813 to the helm chart
