### ISSUE TITLE
[haste] Change to upstream

### ISSUE THREAD

**Issue by nicholaswilde** [k8s-at-home/container-images#103]
# Details

**Image name:** Haste

**Describe the solution you'd like:**

Change from the nodejs version to the [upstream version](https://github.com/seejohnrun/haste-server) per the Discord discussion

**Anything else you would like to add:**

None.

**Additional Information:**

None.

**Comment by onedr0p** [comment]
@nicholaswilde can you rename this to `haste-server` to keep the same name as the upstream project name?

**Comment by nicholaswilde** [comment]
> @nicholaswilde can you rename this to `haste-server` to keep the same name as the upstream project name?

@onedr0p Done!
