### ISSUE TITLE
[goss] add checks

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/container-images#12]
Applications:

- [x] Radarr
- [x] Sonarr
- [x] Jackett
- [x] Lidarr
- [x] Sabnzbd
- [x] Bazarr
- [x] NZBGet
- [x] NZBHydra2
- [x] Plex Media Server
- [x] Tautulli
- [x] xTeVe
- [x] qBittorrent
- [ ] emby - add ports

**Comment by Ornias1993** [comment]
For most of the *arr containers one could just call the API and expect a certain response.
That works quite nicely in my experience...

**Comment by Ornias1993** [comment]
@onedr0p I don't think this was supposed to be closed with #38 yet, as #38 is just for jackett and this issue is global.

**Comment by onedr0p** [comment]
Correct, that was an automated close lol

**Comment by nicholaswilde** [comment]
Added emby to list to add ports.

**Comment by Ornias1993** [comment]
Emby has a strange bug where http requests work but the http port scan fails.

**Comment by onedr0p** [comment]
Going to close this issue after that PR is merged. I have noted in each goss file a `TODO` if there's some odd failure
