### ISSUE TITLE
[actions-runner] add in arm64 support

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/container-images#13]
Adding in arm64 support for each binary in the image would allow us to build multi-arch images for this.

**Comment by bjw-s** [comment]
Should be fixed by #22. That adds targetplatform specific binaries for all tools. Only exception is `taskfile` since that's only compatible with amd64.

**Comment by onedr0p** [comment]
We can revisit go-task if anyone wants it for arm64
