### ISSUE TITLE
Bazarr - Change to deployment strategy

### ISSUE THREAD

**Issue by morpheus65535** [k8s-at-home/container-images#130]
You should use the bazarr.zip asset of each release/pre-release instead of tarball because it doesn't include frontend/build directory.

https://github.com/k8s-at-home/container-images/blob/f6f09a0c80fcb50035893483ef66661c40378a47/apps/bazarr/Dockerfile#L25

**Comment by onedr0p** [comment]
Thanks @morpheus65535 for letting us know, I'll get on it tonight!
