### ISSUE TITLE
Allow ttrss to run at specific path - like /tt-rss/ (suggestion included)

### ISSUE THREAD

**Issue by cr1st1p** [k8s-at-home/container-images#150]
# Details

**Image name:** ttrss

**Describe the solution you'd like:**
I want to have ttrss running in a subdir and not at the root of some domain.

**Anything else you would like to add:**

**Additional Information:**
Solution would be to have some new chart value (default empty), sent as environment variable; and in entrypoint.sh, if env is present and not empty, add an nginx rewrite rule in the sites-available/default file.

For now, I'm using the 'command' value to do it like this - to have it run under path '/tt-rss' (your script could be better and nicer):
```
        command:
        - /bin/sh
        - "-c"
        - sed -i -E -e  's@(root /app;)@\1rewrite ^/*tt-rss/?(.*)$ /\$1;@gi' /etc/nginx/sites-available/default ; /entrypoint.sh
```

**Comment by onedr0p** [comment]
If you've tested this and it works feel free to open a PR :)

**Comment by angelnu** [comment]
@cr1st1p - yep, taking an optional env variable and processing it within `entrypoint.sh` is better than doing it from the command. So the PR is welcomed.
