### ISSUE TITLE
letsencrypt trust issues

### ISSUE THREAD

**Issue by halkeye** [k8s-at-home/container-images#152]
# Details

**Image name:** sonarr (probably more)

**What steps did you take and what happened:**

Tries to connect to my internal nzbget server, which is protected by a letsencrypt certificate. It spits out a big error.

```
sonarr-74d774656-q7rjm sonarr [v3.0.6.1265] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to NzbGet. Error: TrustFailure (Authentication failed, see inner exception.): 'https://nzbget.int.g4v.dev/jsonrpc' ---> System.Net.WebException: Error: TrustFailure (Authentication failed, see inner exception.): 'https://nzbget.int.g4v.dev/jsonrpc' ---> System.Net.WebException: Error: TrustFailure (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

**What did you expect to happen:**

It connect successfully

**Anything else you would like to add:**

Sept 30th lets encrypt updated its root trust server. I'm guessing the mono installs don't have anything remotely modern

https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

When i call curl it works fine so I think its just not importing them into mono

https://www.mono-project.com/docs/faq/security/#i-imported-the-root-certificate-but-it-still-doesnt-work

something like mozroots --import is probably needed but i'm just guessing

**Additional Information:**

**Comment by halkeye** [comment]
https://github.com/tianon/docker-mono/blob/master/3.12.0/Dockerfile#L18

**Comment by halkeye** [comment]
https://howtoinstall.co/en/ca-certificates-mono might be another option

**Comment by onedr0p** [comment]
What's up @halkeye !? 👋🏼 Would running `apt-get install ca-certificates` also solve the issue? That's how I solved it on a machine I manage. I could include that to forcibly make sure the CAs are up to date in all images.

**Comment by onedr0p** [comment]
I went ahead and added that to the sonarr images. You'll probably have to set your image pull policy to always to make sure you grab the updated one.

**Comment by onedr0p** [comment]
Also if using our nzbget image make sure you swap to the nzbget-testing image, there was issues reported with the official release so we had to build their testing image. 

You would have noticed this if you were in our Discord ;)

**Comment by halkeye** [comment]
As I said curl from inside the container worked fine. I think like java mono has its own certificate store. I think you need the mono CA certificates package.

I'll see if I get a minute to try the new image though

**Comment by onedr0p** [comment]
Thanks, yeah and I am not sure either what fixes this completely. All I know is from my investigation and other users in Discord the problem appears to be fixed :/

**Comment by halkeye** [comment]
Looks like I was 2 versions behind on sonarr too (weird that sonarr never let me know), and radarr worked fine, so donno but its fixed now
