### ISSUE TITLE
[dashmachine] Add Image

### ISSUE THREAD

**Issue by carpenike** [k8s-at-home/container-images#16]
Project does not maintain proper tagging.

Project provided Docker Images: https://hub.docker.com/r/rmountjoy/dashmachine/tags?page=1&ordering=last_updated

Project provided Dockerfile: https://github.com/rmountjoy92/DashMachine/blob/master/Dockerfile

Project provided versioning: https://github.com/rmountjoy92/DashMachine/releases/tag/v0.5-4.2

**Comment by onedr0p** [comment]
These tags are not really uniform in any way. No updates from May, and issues and PRs are pretty stacked, is this project abandoned?

**Comment by carpenike** [comment]
Gonna close this as the upstream project is a bit of a mess. May revisit some time in future.
