### ISSUE TITLE
Sonarr v3.0.6.1342 SSL Cert failures (CERTIFICATE_VERIFY_FAILED)

### ISSUE THREAD

**Issue by wingy3181** [k8s-at-home/container-images#160]
# Details

**Image name:**

sonarr

**What steps did you take and what happened:**

I have two separate machines that have sonarr running on image v3.0.6.1342

On one machine it is able to connect to my indexers
On another machine there are errors around SSL certificate failures. e.g. CERTIFICATE_VERIFY_FAILED 

I noticed via docker images that although they are the same tag. They have different SHAs and build times

One machine it is 3c54d28b (9 days ago) <==== not working
On another it is e50ab8369a0e (1 month ago) <==== working

and inspecting the images I can see different steps which i believe is due to following commit

https://github.com/k8s-at-home/container-images/commit/cd33f1570d84b88e805fa1840c0555c421b2fb08#diff-5c17af5a02eeacf1909345af3f287911596bf30cf6f4f594196b5bba15aa39dc

**What did you expect to happen:**

Be able to connect to indexer without SSL certificate failures

**Anything else you would like to add:**

**Additional Information:**

**Comment by wingy3181** [comment]
Just curious about why the new changes (from the last 9 days) was not published as a new tag/version?

**Comment by onedr0p** [comment]
> Just curious about why the new changes (from the last 9 days) was not published as a new tag/version?

Long story short is we follow upstream tags and try to adhere to semver when the application supports it. We simply cannot add our own tags to these images (very hard to keep track of application version and our would be version) or append a build tag like LSIO does because it breaks semver automations in apps like Flux, Argo and Renovatebot. Therefore our container images tags are not immutable.

I would suggest pulling the latest version tag on the one that's broken and it should work. Also, in our sonarr image it weird issues with certs on ARM running in a container.

**Comment by wingy3181** [comment]
Thanks for the quick reply...

I tried already to pull the latest version and also did it just then (and also removed the image locally to pull it remotely again)

From https://github.com/k8s-at-home/container-images/pkgs/container/sonarr I believe the latest tag is v3.0.6.1342

It seems like the latest image is the one with the issues with SSL certificates...

But you maybe right about certs on ARM

The machine that works is still Intel where as the other machine is ARM..

When you say the sonarr image has weird issues with certs on ARM running in a container is there any details to this?
Or this is due to Sonnar devs using Mono which ultimately will have issues on ARM and they need to migrate to dotnet for this to be resolved?

**Comment by wingy3181** [comment]
Looks like ARM issue you mentioned

I pulled latest image on the working one and it is still working on the Intel machine

Thanks for that

**Comment by wingy3181** [comment]
Yep found this
https://github.com/Sonarr/Sonarr/issues/4113

Will close this issue now..thanks again for your help
