### ISSUE TITLE
[bazarr] Add dos2unix for cleansubs script

### ISSUE THREAD

**Issue by Infray** [k8s-at-home/container-images#162]
# Details

**Image name:** Bazarr

**Describe the solution you'd like:** 
Would it be possible to add the dos2unix package to the bazarr image to allow following post-processing script to work:
https://github.com/TheCaptain989/bazarr-cleansubs/blob/master/cleansubs.sh

**Anything else you would like to add:**

**Additional Information:**

**Comment by onedr0p** [comment]
Sounds like a good idea, are you able to submit a PR on the Bazaar dockerfile?

**Comment by Infray** [comment]
I created a PR, can't seem to link it to this issue though, I mentioned the issue as a comment

**Comment by bjw-s** [comment]
Should be fixed now that your PR has been merged. Can you confirm?

**Comment by Infray** [comment]
it seems to work, thanks!
