### ISSUE TITLE
Emby missing CA certs

### ISSUE THREAD

**Issue by mdallaire** [k8s-at-home/container-images#166]
# Details

**Image name:**

k8s-at-home emby chart 3.1.0 using k8s-at-home image v4.6.5.0

**What steps did you take and what happened:**

First sign of the issue was that pushover notification are failing, looking at the logs there are several occurence of the following error:
 `	System.Net.Http.HttpRequestException: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
	 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.`

I am also having issue accessing the plugin catalog and it results in the same error.

**What did you expect to happen:**

Pushover notifications should work and accessing the catalog should too.

**Anything else you would like to add:**

Adding ca-certificates-mono to the build would probably fix this.

**Comment by onedr0p** [comment]
Please open a PR of you think that will solve it, no maintainers here use Emby.

**Comment by mdallaire** [comment]
Looking at the latest [ Emby release notes](https://emby.media/emby-server-466-released.html) it looks that it is an issue with emby that is now fixed.

>  Fix outgoing SSL errors on some Linux distros

This version was released on November 18. How are the container build triggered in this repo? The VERSION file shows 4.6.7.0 but the latest image in ghcr.io/k8s-at-home/emby is 4.6.5.0

**Comment by mdallaire** [comment]
Nevermind, I am seeing that the automatic build is failing for some reason. I am going to try to figure out why and submit a PR.

**Comment by mdallaire** [comment]
So I have forked the repo, ran the release workflow and [Emby 4.6.7.0 built right away](https://github.com/mdallaire/container-images/pkgs/container/emby) without me having to change anything. Since it seems like a one time issue with the build could you do a manual workflow run on it?

**Comment by mdallaire** [comment]
I see it just built successfully. Thanks!
