### ISSUE TITLE
32-bit arm builds

### ISSUE THREAD

**Issue by utkuozdemir** [k8s-at-home/container-images#172]
# Details

**Image name:**
(all)

**Describe the solution you'd like:**

To have 32-bit arm builds (armv7 and/or armv6)

**Anything else you would like to add:**

Would you consider providing builds for architectures other than amd64 and arm64?
I need it specifically for wireguard, but I think it would be beneficial for all images since some people use raspberry pi clusters.

**Comment by onedr0p** [comment]
I'm not totally against it but I'm curious what devices you are running kubernetes on that after only armv7? We originally only wanted to support arm64 and amd64 as these are the most popular and only focusing on 2 platforms is much less maintenance on us.

**Comment by utkuozdemir** [comment]
I'm using Raspberry Pi OS on a rpi2, rpi3 and a rpi400. Rpi OS has a 64-bit version but it is beta since a long time and only supports rpi version >=3.

**Comment by onedr0p** [comment]
Those pi are old, only have 100mbit network and very low memory and cpu. Honestly I would not even use them in kubernetes. With the k8s overhead, you could probably run at most like 1 of these apps in this repo on them.

**Comment by utkuozdemir** [comment]
As control plane node you are right. But as worker node they are doing ok for a few apps.

**Comment by onedr0p** [comment]
I would like to accommodate armv7 but I'm not sure if it's really worth the cycles to implement.  Some of these apps could easily be updated to build while others wouldn't be. Some of these apps are being compiled from source during the build. I have a sneaky suspicion that arm might take too long to compile.

Take qbittorrent as an example the arm64 build takes about 40 minutes to complete. Wireguard is also being compiled from source. armv7 is just very old and not used as much anymore.

**Comment by utkuozdemir** [comment]
Got it, it was just a suggestion since I had a concrete use case. If you conclude that it's not worth it, it's totally fine. Probably I'll end up building wireguard image for armv7 myself.

I just recommend thinking about it because there are many rpi clusters out there and your great set of apps can bring value to them.

Cheers.
