### ISSUE TITLE
Build failed for `qbittorrent`

### ISSUE THREAD

**Issue by alinbalutoiu** [k8s-at-home/container-images#175]
The image for `qbittorrent` `v4.4.0` failed (see [details here](https://github.com/k8s-at-home/container-images/runs/4734143548?check_suite_focus=true)). You can check that the [repo doesn't contain the v4.4.0 tag](https://github.com/k8s-at-home/container-images/pkgs/container/qbittorrent).

It looks that the version of `qt5-qmake` [being installed](https://packages.ubuntu.com/focal/qt5-qmake) is older than the minimum required by `qbittorrent`.

```
#9 6.449 checking for Qt5 qmake >= 5.15.2... not found
#9 6.450 configure: error: Could not find qmake
```

**Comment by onedr0p** [comment]
Thanks for reporting, I'll take a look when I get a moment.

**Comment by onedr0p** [comment]
Looking at the qbittorrent github issues seems like people have been reporting a lot of issues with qb 4.4.0. I am also not seeing a clear way for us to install qt6 without compiling it from source :(

**Comment by onedr0p** [comment]
Looks like we are going to have to wait until Ubuntu gets a PPA for the qt6 deps

```
#8 6.571 checking for Qt5 qmake >= 5.15.2... not found
#8 6.571 configure: error: Could not find qmake
------
Dockerfile:69
--------------------
  68 |     # Compile qbitorrent
  69 | >>> RUN \
  70 | >>>   git clone --depth 1 -b "release-${VERSION}" https://github.com/qbittorrent/qBittorrent.git . \
  71 | >>>   && ./configure "${EXTRA_CFG_ARG}" --disable-gui --disable-stacktrace --disable-qt-dbus \
  72 | >>>   && make \
  73 | >>>   && make install \
  74 | >>>   && strip /usr/local/bin/qbittorrent-nox -o /usr/local/bin/qbittorrent-nox-stripped
  75 |     
--------------------
error: failed to solve: process "/bin/sh -c git clone --depth 1 -b \"release-${VERSION}\" https://github.com/qbittorrent/qBittorrent.git .   && ./configure \"${EXTRA_CFG_ARG}\" --disable-gui --disable-stacktrace --disable-qt-dbus   && make   && make install   && strip /usr/local/bin/qbittorrent-nox -o /usr/local/bin/qbittorrent-nox-stripped" did not complete successfully: exit code: 1
```

**Comment by onedr0p** [comment]
@alinbalutoiu can you please try out the newest build? I switch from compile qb to pulling in the binary from https://github.com/userdocs/qbittorrent-nox-static

**Comment by alinbalutoiu** [comment]
Thanks for looking into that!

The image seems to be working fine, though the logs gets spammed for roughly 10 seconds during the startup with the following lines:
```
...
Numeric mode unsupported in the posix collation implementation
Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Case insensitive sorting unsupported in the posix collation implementation
Numeric mode unsupported in the posix collation implementation
Only C and default locale supported with the posix collation implementation
Numeric mode unsupported in the posix collation implementation
Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Case insensitive sorting unsupported in the posix collation implementation
Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
Only C and default locale supported with the posix collation implementation
...
```

After the startup phase everything looks good 👍

**Comment by onedr0p** [comment]
According to the userdoc release notes

> Binary builds are not stripped by default to preserve stacktrace / debugging features built into qBittorrent.

I'm guessing that's why those messages are showing up. I can strip the binary of those debugging features like we were doing before.

**Comment by alinbalutoiu** [comment]
I think it would be a good idea to do that.

The image looks good, haven't noticed any issues with it so far 👍
