### ISSUE TITLE
404 "Please check our quick-start guides first."

### ISSUE THREAD

**Issue by jhalbrecht** [k8s-at-home/container-images#185]
# Details

While attempting to install plex on TrueNas Scale -> apps -> Truecharts -> plex and RTFM I encountered a 404

On this page https://truecharts.org/apps/stable/plex/ under Support https://truecharts.org/apps/stable/plex/#support I note the first bullet item is "Please check our quick-start guides first." However it's link, https://truecharts.org/manual/Quick-Start%20Guides/01-Open-Apps/, is broken.

Does a quick start guide exist? I'd like to read it.

**Comment by bjw-s** [comment]
Wouldnt this issue be better suited for the Truecharts repo? We are not affiliated with that project.
