### ISSUE TITLE
[sabnzbd] Add pynzbget python module to container image

### ISSUE THREAD

**Issue by sirance** [k8s-at-home/container-images#212]
Would it be possible to add the pynzbget python module to the list of installed modules in the sabnzbd container, as this would then allow use of the NZB-Notify scripts (https://github.com/caronc/nzb-notify) which are really useful for notifications from sabnzbd.

**Comment by sirance** [comment]
I'm not too sure what extra it provides, however it is listed in the script's requirements.txt

Installing it via pip into the container would be perfect thanks.

**Comment by onedr0p** [comment]
Done in https://github.com/k8s-at-home/container-images/commit/205a7f8bf96f09b2743e44490af77a976ca7bd0c
