### ISSUE TITLE
Emby container did not build with new version

### ISSUE THREAD

**Issue by mdallaire** [k8s-at-home/container-images#224]
# Details

**Image name:**

emby

**What steps did you take and what happened:**

The build log show it failed to fetch the latest version(https://github.com/k8s-at-home/container-images/runs/7060668421?check_suite_focus=true#step:9:479)

**Additional Information:**

It seems to happen once in a while for this container image.

**Comment by onedr0p** [comment]
Please use `ghcr.io/onedr0p/emby:4.7.5.0` until we are ready to migrate all our changes from https://github.com/onedr0p/containers over to this repo.

**Comment by mdallaire** [comment]
I don't think the build is broken since the build on my PR seems to have completed successfully https://github.com/k8s-at-home/container-images/runs/7342775013?check_suite_focus=true.

I think there is a delay between their release and the availability of the RPM for download which may be what is breaking the build when there is a fresh release.

I changed my hr values to use your image for now. Thanks!

**Comment by onedr0p** [comment]
I figured, I've seen that before. When this repo is synced with mine that won't be a problem anymore, the containers will continue to build until they succeed.

**Comment by onedr0p** [comment]
Also, both repos will have eventual consistency. Just note that https://github.com/onedr0p/containers is more of a place to test out changes before bringing them here, there shouldn't be any breaking changes unless I am actively testing something.
