### ISSUE TITLE
Prowlarr image to old

### ISSUE THREAD

**Issue by Y0ngg4n** [k8s-at-home/container-images#232]
# Details

**Image name:** Prowlarr

**What did you expect to happen:** 
Having the latest image

**Additional Information:**

The latest version is 0.4.3.1921
but the current version in the package repo is only v0.4.0.1802

**Comment by onedr0p** [comment]
did you try the prowlarr-develop or prowlarr-nightly tags?

Look here https://github.com/orgs/k8s-at-home/packages?repo_name=container-images

**Comment by Y0ngg4n** [comment]
@onedr0p no did not tried them. But thought 0.4.3 is a stable release?

**Comment by onedr0p** [comment]
afaik there is no stable prowlarr release.

**Comment by Y0ngg4n** [comment]
ah ok thank you.
