### ISSUE TITLE
fix issue where version file is updated with no version

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/container-images#31]
For example: https://github.com/k8s-at-home/container-images/commit/8a7cc307ad178ce84a852000b3834cb40e59168d

This is causing images to get rebuilt. I think I should be able to not have it write to a version file if none is returned, the curl requests errors out

**Comment by onedr0p** [comment]
Maybe a step after here that gracefully dies if VERSION=""

https://github.com/k8s-at-home/container-images/blob/main/.github/workflows/appdaemon.yaml#L31

**Comment by onedr0p** [comment]
This doesn't look promising, maybe need to tackle this another way.

https://stackoverflow.com/a/57907146/10496442

**Comment by bjw-s** [comment]
Maybe we could do something like this: https://github.community/t/if-expression-with-context-variable/16558/6

`if: ${{ steps.prep.outputs.VERSION }}`

**Comment by onedr0p** [comment]
I think that might be the way, for now at least
