### ISSUE TITLE
[network-ups-tools] How to run upsmon as well?

### ISSUE THREAD

**Issue by cdeadspine** [k8s-at-home/container-images#35]
Hello, what is the best way to also run upsmon with this image? 
Specifically from the helm chart.

Is there a standard way to alter the image CMD so it does something like,
' sleep 10 ; /usr/local/ups/sbin/upsmon ' & (in the background somehow?)    &&  "/entrypoint.sh"

**Comment by bjw-s** [comment]
I just commented on #36, let's move the further discussion there.
