### ISSUE TITLE
[wireguard] Entrypoint fails when ipv6 is disabled

### ISSUE THREAD

**Issue by bjw-s** [k8s-at-home/container-images#46]
Based on discussion in our Discord there might be an issue with the Wireguard VPN shim failing when IPv6 is disabled.
I noticed that the iptables `OUTPUT` chain for IPv4 and IPv6 always gets flushed, potentially causing the script to fail.

**Potential solution(s)**
- Move both lines inside the `if ... then` block. Not 100% sure anymore why I didn't before, so needs some testing to see if everything would still work.
- Add an additional check to see if IPv6 is enabled before trying to run the related steps. This could also be used to display a warning when `KILLSWITCH_EXCLUDEDNETWORKS_IPV6` is set but there is no IPv6 support.
- All of the above 🙂

**Comment by disconn3ct** [comment]
/reopen

ipv6 is disabled in the kernel. I'm 99% sure this is the same bug:
```
[#] iptables-restore -n
[#] /config/up.sh wg0
[WARNING] sysctl net.ipv4.conf.all.src_valid_mark=1 is not set. This may prevent the killswitch from working properly and may prevent outbound network access.
ip6tables v1.8.4 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
[ERROR] Received non-zero exit code (3) executing the command source "/shim/killswitch.sh" on line 10.
[INFO] Shutting down VPN!
```
