### ISSUE TITLE
Include a prefix of v on all container image tags

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/container-images#8]
There's a YAML / Helm issue where if the tag is a decimal and ends with 0 (e.g. `21.0`) Helm template, Flux, Flux2 will strip out the `.0` leaving the container image tag as e.g. `nzbget:21`.

A solution to this could be to include a prefix of `v` on the tag (e.g. `v21.0`) which will force helm and others to treat it like a string.

**Comment by carpenike** [comment]
Wasn’t the whole point of moving away from lsio to use semver tagging?

**Comment by onedr0p** [comment]
According to https://semver.org/#is-v123-a-semantic-version only a tag like `1.0.0` is proper semver, which we are currently doing. 

My suggestion is to add a prefix of `v` to the tag so we force helm and flux to take it as a string.

**Comment by carpenike** [comment]
Right... but if we're going to do that then why not just use lsio images? I get that there's other issues related to root and s6 that don't play as nicely in K8S.

**Comment by carpenike** [comment]
Seems like the ask should be placed on flux/helm to properly support semver....

**Comment by onedr0p** [comment]
> Right... but if we're going to do that then why not just use lsio images? I get that there's other issues related to root and s6 that don't play as nicely in K8S.

LSIO doesn't do even `v1.0.0` or `1.0.0` tags, they messed it up with adding `version-` prefix to that, so they have `version-v1.0.0`. Their tagging methods are bonkers. When I bought this up in the PR they had to refactor the tags they shot me down with some nonsense reasons.

> Seems like the ask should be placed on flux/helm to properly support semver....

They technically do, the issue with how they treat docker tags that end in a `.0`

**Comment by carpenike** [comment]
> LSIO doesn't do even v1.0.0 or 1.0.0 tags, they messed it up with adding version- prefix to that, so they have version-v1.0.0. Their tagging methods are bonkers. When I bought this up in the PR they had to refactor the tags they shot me down with some nonsense reasons.

Well sure, but a string is a string. :)

Why not just require all minor revisions to start with 1 rather than 0?

**Comment by onedr0p** [comment]
> Well sure, but a string is a string. :)

I am not looking to convince Flux or other tools like watchtower, duin to support LSIO `version-` prefix. Tools like those can much easily interpret `v1.0.0` over `version-v1.0.0`

> Why not just require all minor revisions to start with 1 rather than 0?

First issue is what happens when the developer of the app releases 21.1, that would override the previous 21.1 which was 21.0. That is messy. Moreover, we are not the developers of the apps, we do not control their version scheme. The only thing we do is sanitize the incoming version to match semver e.g. (`x.x.x`)

**Comment by onedr0p** [comment]
fixed in https://github.com/k8s-at-home/container-images/commit/6bbeea03128a79c2881303ccf4783cb0d654b890
