### ISSUE TITLE
[reg] Package visibility

### ISSUE THREAD

**Issue by nicholaswilde** [k8s-at-home/container-images#87]
# Details

**Image name:**

reg

**What steps did you take and what happened:**

N/A

**What did you expect to happen:**

N/A

**Anything else you would like to add:**

Please make the reg package public. It is currently private.

[https://github.com/orgs/k8s-at-home/packages/container/package/reg](https://github.com/orgs/k8s-at-home/packages/container/package/reg)

**Additional Information:**

N/A

**Comment by bjw-s** [comment]
Done! 👍🏻
